{{ if and (.Files.Glob "files/httpd.conf") (not .Values.httpdConfConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apache.fullname" . }}-httpd-conf
  labels:
    app.kubernetes.io/name: {{ include "apache.fullname" . }}
    helm.sh/chart: {{ include "apache.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/httpd.conf").AsConfig | indent 2 }}
{{ end }}